# Imports

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

# Load Data

In [2]:
column_descrip = pd.read_csv('../../data/raw/usgs/usgs_data_dictionary.csv')
column_descrip

,field,category,description,type,non-missing,Labels,Min,Max
0,case_id,id,unique uswtdb id,long,72130.0,NaN,3.000001e+06,3.124485e+06
1,faa_ors,id,faa digital obstacle file (dof) for obstacle r...,str9,66586.0,NaN,NaN,NaN
2,faa_asn,id,faa obstruction evaluation - airport airspace ...,str17,66877.0,NaN,NaN,NaN
3,usgs_pr_id,id,usgs id from prior turbine dataset,long,38095.0,NaN,1.000000e+00,4.913500e+04
4,eia_id,id,eia plant id from eia form 860,long,65445.0,NaN,9.000000e+01,6.527000e+04
5,t_state,location,state where turbine is located,str2,72130.0,NaN,NaN,NaN
6,t_county,location,county where turbine is located,str31,72130.0,NaN,NaN,NaN
7,t_fips,location,state and county fips where turbine is located,str5,72130.0,NaN,NaN,NaN
8,p_name,project characteristic,project name,str42,72130.0,NaN,NaN,NaN
9,p_year,project characteristic,year project became operational,int,71398.0,NaN,1.981000e+03,2.022000e+03
10,p_tnum,project characteristic,number of turbines in project,int,72130.0,NaN,1.000000e+00,7.310000e+02
11,p_cap,project characteristic,project capacity (MW),double,68204.0,NaN,5.000000e-02,1.055600e+03
12,t_manu,turbine characteristic,turbine original equipment manufacturer,str31,67045.0,NaN,NaN,NaN
13,t_model,turbine characteristic,turbine model,str18,66908.0,NaN,NaN,NaN
14,t_cap,turbine characteristic,turbine capacity (kW),int,67216.0,NaN,5.000000e+01,6.000000e+03
15,t_hh,turbine characteristic,turbine hub height (meters),double,66685.0,NaN,1.900000e+01,1.370000e+02
16,t_rd,turbine characteristic,turbine rotor diameter (meters),double,66778.0,NaN,1.340000e+01,1.550000e+02
17,t_rsa,turbine characteristic,turbine rotor swept area (meters^2),double,66778.0,NaN,1.410300e+02,1.886919e+04
18,t_ttlh,turbine characteristic,turbine total height - calculated (meters),double,66685.0,NaN,3.040000e+01,2.054000e+02
19,retrofit,turbine characteristic,indicator of whether the turbine has been part...,byte,72130.0,NaN,0.000000e+00,1.000000e+00
20,retrofit_year,turbine characteristic,year in which turbine was retrofitted,int,6738.0,NaN,2.015000e+03,2.021000e+03
21,t_conf_atr,turbine characteristics qa/qc,turbine characteristic confidence (0-3),byte,72130.0,see below,1.000000e+00,3.000000e+00
22,t_conf_loc,visual inspection qa/qc,location confidence (0 -3),byte,72130.0,see below,1.000000e+00,3.000000e+00
23,t_img_date,visual inspection info,date of image used to visually verify turbine ...,int,63984.0,NaN,NaN,NaN
24,t_img_srce,visual inspection info,source of image used to visually verify turbin...,str16,72130.0,NaN,NaN,NaN
25,xlong,location,longitude (decimal degrees - NAD 83 datum),double,72130.0,NaN,-1.717131e+02,1.447227e+02
26,ylat,location,latitude (decimal degrees - NAD 83 datum),double,72130.0,NaN,1.338940e+01,6.683990e+01
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Acronyms,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,ASN,Aeronautical Study Number,NaN,NaN,NaN,NaN,NaN,NaN
31,ACP,American Clean Power Association,NaN,NaN,NaN,NaN,NaN,NaN
32,DOF,Digital Obstacal File,NaN,NaN,NaN,NaN,NaN,NaN
33,FAA,Federal Avaiation Administration,NaN,NaN,NaN,NaN,NaN,NaN
34,LBNL,Lawrence Berkeley National Laboratory,NaN,NaN,NaN,NaN,NaN,NaN
35,OE/AAA,Obstacle Evaluation / Airport Airspace Analysis,NaN,NaN,NaN,NaN,NaN,NaN
36,ORS,Obstacle Repository System,NaN,NaN,NaN,NaN,NaN,NaN
37,USGS,United States Geological Survey,NaN,NaN,NaN,NaN,NaN,NaN
38,EIA,Energy Information Administration,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,t_conf_loc,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,code,short description,long description,NaN,NaN,NaN,NaN,NaN
42,0,Not visually verified,Not visually verified: Point has not been visu...,NaN,NaN,NaN,NaN,NaN
43,1,No confidence,No confidence: No turbine shown in image; imag...,NaN,NaN,NaN,NaN,NaN
44,2,Partial confidence,Partial confidence: image shows a developed pa...,NaN,NaN,NaN,NaN,NaN
45,3,Full confidence,Full confidence: image shows an installed turb...,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,t_conf_atr,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,code,short description,long description,NaN,NaN,NaN,NaN,NaN
49,0,Not verified,Not verified: attributes have not been verified,NaN,NaN,NaN,NaN,NaN
50,1,No confidence,"No confidence: no facility data, no name, noth...",NaN,NaN,NaN,NaN,NaN
51,2,Partial confidence,Partial confidence: incomplete information or ...,NaN,NaN,NaN,NaN,NaN
52,3,Full confidence,Full confidence: consistent information across...,NaN,NaN,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,retrofit,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,code,short description,long description,NaN,NaN,NaN,NaN,NaN
56,0,No,Turbine has not been significantly retrofitted...,NaN,NaN,NaN,NaN,NaN
57,1,Yes,Turbine has been significantly retrofitted (i....,NaN,NaN,NaN,NaN,NaN

In [3]:
useful_columns = ['case_id','t_state','t_county','t_fips','p_name','p_year',
                  'p_tnum','p_cap','t_manu','t_model','t_cap','t_hh','t_rd',
                  't_rsa','t_ttlh','xlong','ylat']

In [4]:
column_descrip[column_descrip['field'].isin(useful_columns)][['field','description']]

       field                                     description
0    case_id                                unique uswtdb id
5    t_state                  state where turbine is located
6   t_county                 county where turbine is located
7     t_fips  state and county fips where turbine is located
8     p_name                                    project name
9     p_year                 year project became operational
10    p_tnum                   number of turbines in project
11     p_cap                           project capacity (MW)
12    t_manu         turbine original equipment manufacturer
13   t_model                                   turbine model
14     t_cap                           turbine capacity (kW)
15      t_hh                     turbine hub height (meters)
16      t_rd                 turbine rotor diameter (meters)
17     t_rsa             turbine rotor swept area (meters^2)
18    t_ttlh      turbine total height - calculated (meters)
25     xlong      longitude (decimal degrees - NAD 83 datum)
26      ylat       latitude (decimal degrees - NAD 83 datum)

In [5]:
df = pd.read_csv('../../data/raw/usgs/usgs_data.csv',
                 engine='python',encoding='latin1',usecols=useful_columns)
# We want only New York data
df = df[df.t_state=='NY']

In [6]:
df.head()

,case_id,t_state,t_county,t_fips,p_name,p_year,p_tnum,p_cap,t_manu,t_model,t_cap,t_hh,t_rd,t_rsa,t_ttlh,xlong,ylat
1528,3075480,NY,Chautauqua County,36013,Arkwright Summit,2018.0,36,78.4,Vestas,V110-2.0,2200.0,95.0,110.0,9503.32,150.0,-79.230286,42.395222
1529,3075488,NY,Chautauqua County,36013,Arkwright Summit,2018.0,36,78.4,Vestas,V110-2.0,2200.0,95.0,110.0,9503.32,150.0,-79.245026,42.427578
1530,3075460,NY,Chautauqua County,36013,Arkwright Summit,2018.0,36,78.4,Vestas,V110-2.0,2200.0,95.0,110.0,9503.32,150.0,-79.222168,42.388699
1531,3075489,NY,Chautauqua County,36013,Arkwright Summit,2018.0,36,78.4,Vestas,V110-2.0,2000.0,95.0,110.0,9503.32,150.0,-79.252396,42.430599
1532,3075456,NY,Chautauqua County,36013,Arkwright Summit,2018.0,36,78.4,Vestas,V110-2.0,2000.0,95.0,110.0,9503.32,150.0,-79.232803,42.430202